
rptdata.fact_sim_bill_detail （模拟出账）

set mapreduce.job.name=${DEST_TBL_SCHEMA}.fact_sim_bill_detail_${SRC_FILE_DAY};
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.dynamic.partition=true;
set hive.optimize.sort.dynamic.partition=true;

alter table ${DEST_TBL_SCHEMA}.fact_sim_bill_detail drop IF EXISTS partition(src_file_day='${SRC_FILE_DAY}');
--------------------
--每月第一天逻辑
--------------------
insert overwrite table ${DEST_TBL_SCHEMA}.fact_sim_bill_detail partition (src_file_day='${SRC_FILE_DAY}', bill_day)
--合约按月快照出存量，只出BOSS合约
select
	b.order_id                      ,
	b.order_last_upt_time           ,
	b.order_item_id                 ,
	b.payment_type                  ,
	b.currency_type                 ,
	b.order_status                  ,
	b.order_crt_day                 ,
	b.order_cancel_day              ,
	b.client_ip_region_id           ,
	b.payment_msisdn_region_id      ,
	b.order_msisdn_region_id        ,
	b.plat_id                       ,
	b.channel_id                    ,
	b.term_prod_id               ,
	b.term_prod_version_id       ,
	b.trig_order_program_id         ,
	b.trig_order_series_program_id  ,
	b.payment_msisdn                ,
	b.sp_id                         ,
	b.operation_code                ,
	b.goods_id                      ,
	b.goods_type                    ,
	b.goods_name                    ,
	b.service_code                  ,
	b.service_name                  ,
	b.order_crt_time                ,
	b.order_accept_time             ,
	b.order_payment_time            ,
	b.order_cancel_time             ,
	b.client_ip                     ,
	b.app_name                      ,
	b.order_user_id                 ,
	b.order_user_num                ,
	b.order_opr_user_id             ,
	b.order_opr_user_type           ,
	b.cancel_opr_user_id            ,
	b.cancel_opr_user_type          ,
	b.external_order_id             ,
	b.payment_id                    ,
	b.order_source_id               ,
	b.order_source_type             ,
	b.merchant_account              ,
	b.portal_type                   ,
	b.order_program_id              ,
	b.order_series_program_id       ,
	b.product_id                    ,
	b.product_pkg_id                ,
	b.sub_business_id               ,
	b.order_item_delivery_handler   ,
	b.order_item_delivery_status    ,
	b.order_item_auth_type          ,
	b.order_item_auth_unit          ,
	b.order_item_auth_qty           ,
	b.order_item_delivery_qty       ,
	b.order_item_unit_price         ,
	b.order_item_resource_id       ,
	b.order_item_resource_type      ,
	b.order_item_order_begin_time   ,
	b.order_item_order_end_time     ,
	b.order_item_account_type       ,
	b.order_item_account_charge_amt         ,
	b.virtual_operation_flag        ,
	'N' as new_add_flag                  ,
	case when c.phone_num is not null then 'Y' else 'N' end as boss_last_success_bill_flag   ,
	b.payment_amt                   ,
	'${SRC_FILE_DAY}' as bill_day
from intdata.contract_monthly_snapshot a  --月全量合约
join rptdata.fact_order_item_detail b  --日新增订单， 不用限定时间,做全表扫描
on a.order_id = b.order_id and b.order_status in ('5', '9') --已支付订单状态
left join intdata.boss_month_bill c  --aaa_boss月账单
on c.src_file_month='${SRC_FILE_MONTH}' --以统计日为基准的 上个月
and if(a.payment_msisdn is not null and a.payment_msisdn <> '', if(substr(a.payment_msisdn, 1, 2)='86', substr(a.payment_msisdn, 3, 11), a.payment_msisdn), concat('', rand())) = c.phone_num and a.product_id = c.product_id
where a.src_file_month='${SRC_FILE_MONTH}'
and a.contract_payment_type='MOBILE_BOSS' and a.contract_status = 'NORMAL'  --MOBILE_BOSS表示 BOSS合约，那ALI_PAY表示 第三方自动续订

--'${SRC_FILE_MONTH}' 指 上个月， '${SRC_FILE_DAY}' 指 当日

union all
--boss合约和非包周期，只出一次，默认新增
select
	b.order_id                      ,
	b.order_last_upt_time           ,
	b.order_item_id                 ,
	b.payment_type                  ,
	b.currency_type                 ,
	b.order_status                  ,
	b.order_crt_day                 ,
	b.order_cancel_day              ,
	b.client_ip_region_id           ,
	b.payment_msisdn_region_id      ,
	b.order_msisdn_region_id        ,
	b.plat_id                       ,
	b.channel_id                    ,
	b.term_prod_id               ,
	b.term_prod_version_id       ,
	b.trig_order_program_id         ,
	b.trig_order_series_program_id  ,
	b.payment_msisdn                ,
	b.sp_id                         ,
	b.operation_code                ,
	b.goods_id                      ,
	b.goods_type                    ,
	b.goods_name                    ,
	b.service_code                  ,
	b.service_name                  ,
	b.order_crt_time                ,
	b.order_accept_time             ,
	b.order_payment_time            ,
	b.order_cancel_time             ,
	b.client_ip                     ,
	b.app_name                      ,
	b.order_user_id                 ,
	b.order_user_num                ,
	b.order_opr_user_id             ,
	b.order_opr_user_type           ,
	b.cancel_opr_user_id            ,
	b.cancel_opr_user_type          ,
	b.external_order_id             ,
	b.payment_id                    ,
	b.order_source_id               ,
	b.order_source_type             ,
	b.merchant_account              ,
	b.portal_type                   ,
	b.order_program_id              ,
	b.order_series_program_id       ,
	b.product_id                    ,
	b.product_pkg_id                ,
	b.sub_business_id               ,
	b.order_item_delivery_handler   ,
	b.order_item_delivery_status    ,
	b.order_item_auth_type          ,
	b.order_item_auth_unit          ,
	b.order_item_auth_qty           ,
	b.order_item_delivery_qty       ,
	b.order_item_unit_price         ,
	b.order_item_resource_id       ,
	b.order_item_resource_type      ,
	b.order_item_order_begin_time   ,
	b.order_item_order_end_time     ,
	b.order_item_account_type       ,
	b.order_item_account_charge_amt         ,
	b.virtual_operation_flag        ,
	'Y' as new_add_flag                  ,
	'Y' as boss_last_success_bill_flag   ,
	b.payment_amt                   ,
	'${SRC_FILE_DAY}' as bill_day
from rptdata.fact_order_item_detail b  --日新增订单
where b.src_file_day='${SRC_FILE_DAY}' and b.order_status in ('5', '9')
and ((b.order_item_auth_type ='PERIOD' and b.order_item_auth_unit in ('HOUR', 'MINUTE')) or b.order_item_auth_type in ('TIMES', 'BOSS_MONTH'))
and nvl(b.boss_repeat_order_flag, 'N') = 'N'

union all
--非boss合约，默认全部是新增，按天拆分
select 
	t.order_id                      ,
	t.order_last_upt_time           ,
	t.order_item_id                 ,
	t.payment_type                  ,
	t.currency_type                 ,
	t.order_status                  ,
	t.order_crt_day                 ,
	t.order_cancel_day              ,
	t.client_ip_region_id           ,
	t.payment_msisdn_region_id      ,
	t.order_msisdn_region_id        ,
	t.plat_id                       ,
	t.channel_id                    ,
	t.term_prod_id               ,
	t.term_prod_version_id       ,
	t.trig_order_program_id         ,
	t.trig_order_series_program_id  ,
	t.payment_msisdn                ,
	t.sp_id                         ,
	t.operation_code                ,
	t.goods_id                      ,
	t.goods_type                    ,
	t.goods_name                    ,
	t.service_code                  ,
	t.service_name                  ,
	t.order_crt_time                ,
	t.order_accept_time             ,
	t.order_payment_time            ,
	t.order_cancel_time             ,
	t.client_ip                     ,
	t.app_name                      ,
	t.order_user_id                 ,
	t.order_user_num                ,
	t.order_opr_user_id             ,
	t.order_opr_user_type           ,
	t.cancel_opr_user_id            ,
	t.cancel_opr_user_type          ,
	t.external_order_id             ,
	t.payment_id                    ,
	t.order_source_id               ,
	t.order_source_type             ,
	t.merchant_account              ,
	t.portal_type                   ,
	t.order_program_id              ,
	t.order_series_program_id       ,
	t.product_id                    ,
	t.product_pkg_id                ,
	t.sub_business_id               ,
	t.order_item_delivery_handler   ,
	t.order_item_delivery_status    ,
	t.order_item_auth_type          ,
	t.order_item_auth_unit          ,
	t.order_item_auth_qty           ,
	t.order_item_delivery_qty       ,
	t.order_item_unit_price         ,
	t.order_item_resource_id       ,
	t.order_item_resource_type      ,
	t.order_item_order_begin_time   ,
	t.order_item_order_end_time     ,
	t.order_item_account_type       ,
	t.order_item_account_charge_amt         ,
	t.virtual_operation_flag        ,
	'Y' as new_add_flag                  ,
	'Y' as boss_last_success_bill_flag   ,
	t.payment_amt / t.order_item_auth_qty AS payment_amt ,
	substr(regexp_replace(date_add(concat_ws('-', substr(t.order_item_order_begin_time, 1, 4), substr(t.order_item_order_begin_time, 5, 2), substr(t.order_item_order_begin_time, 7, 2)), j.pos), '-', ''), 1, 8) as bill_day
from (
select
	b.order_id                      ,
	b.order_last_upt_time           ,
	b.order_item_id                 ,
	b.payment_type                  ,
	b.currency_type                 ,
	b.order_status                  ,
	b.order_crt_day                 ,
	b.order_cancel_day              ,
	b.client_ip_region_id           ,
	b.payment_msisdn_region_id      ,
	b.order_msisdn_region_id        ,
	b.plat_id                       ,
	b.channel_id                    ,
	b.term_prod_id               ,
	b.term_prod_version_id       ,
	b.trig_order_program_id         ,
	b.trig_order_series_program_id  ,
	b.payment_msisdn                ,
	b.sp_id                         ,
	b.operation_code                ,
	b.goods_id                      ,
	b.goods_type                    ,
	b.goods_name                    ,
	b.service_code                  ,
	b.service_name                  ,
	b.order_crt_time                ,
	b.order_accept_time             ,
	b.order_payment_time            ,
	b.order_cancel_time             ,
	b.client_ip                     ,
	b.app_name                      ,
	b.order_user_id                 ,
	b.order_user_num                ,
	b.order_opr_user_id             ,
	b.order_opr_user_type           ,
	b.cancel_opr_user_id            ,
	b.cancel_opr_user_type          ,
	b.external_order_id             ,
	b.payment_id                    ,
	b.order_source_id               ,
	b.order_source_type             ,
	b.merchant_account              ,
	b.portal_type                   ,
	b.order_program_id              ,
	b.order_series_program_id       ,
	b.product_id                    ,
	b.product_pkg_id                ,
	b.sub_business_id               ,
	b.order_item_delivery_handler   ,
	b.order_item_delivery_status    ,
	b.order_item_auth_type          ,
	b.order_item_auth_unit          ,
	b.order_item_auth_qty           ,
	b.order_item_delivery_qty       ,
	b.order_item_unit_price         ,
	b.order_item_resource_id       ,
	b.order_item_resource_type      ,
	b.order_item_order_begin_time   ,
	b.order_item_order_end_time     ,
	b.order_item_account_type       ,
	b.order_item_account_charge_amt         ,
	b.virtual_operation_flag        ,
	b.payment_amt                   ,
	split(rpad('0',cast(b.order_item_auth_qty as int)-1,'0'),'0') as day_arr
from rptdata.fact_order_item_detail b  --日新增订单
where b.src_file_day='${SRC_FILE_DAY}' and b.order_item_auth_type='PERIOD' and b.order_item_auth_unit='DAY' and b.order_status in ('5', '9')
) t
lateral view posexplode(t.day_arr) j as pos, c1

union all
--非boss合约，默认全部是新增，按月拆分
select
	t.order_id                      ,
	t.order_last_upt_time           ,
	t.order_item_id                 ,
	t.payment_type                  ,
	t.currency_type                 ,
	t.order_status                  ,
	t.order_crt_day                 ,
	t.order_cancel_day              ,
	t.client_ip_region_id           ,
	t.payment_msisdn_region_id      ,
	t.order_msisdn_region_id        ,
	t.plat_id                       ,
	t.channel_id                    ,
	t.term_prod_id               ,
	t.term_prod_version_id       ,
	t.trig_order_program_id         ,
	t.trig_order_series_program_id  ,
	t.payment_msisdn                ,
	t.sp_id                         ,
	t.operation_code                ,
	t.goods_id                      ,
	t.goods_type                    ,
	t.goods_name                    ,
	t.service_code                  ,
	t.service_name                  ,
	t.order_crt_time                ,
	t.order_accept_time             ,
	t.order_payment_time            ,
	t.order_cancel_time             ,
	t.client_ip                     ,
	t.app_name                      ,
	t.order_user_id                 ,
	t.order_user_num                ,
	t.order_opr_user_id             ,
	t.order_opr_user_type           ,
	t.cancel_opr_user_id            ,
	t.cancel_opr_user_type          ,
	t.external_order_id             ,
	t.payment_id                    ,
	t.order_source_id               ,
	t.order_source_type             ,
	t.merchant_account              ,
	t.portal_type                   ,
	t.order_program_id              ,
	t.order_series_program_id       ,
	t.product_id                    ,
	t.product_pkg_id                ,
	t.sub_business_id               ,
	t.order_item_delivery_handler   ,
	t.order_item_delivery_status    ,
	t.order_item_auth_type          ,
	t.order_item_auth_unit          ,
	t.order_item_auth_qty           ,
	t.order_item_delivery_qty       ,
	t.order_item_unit_price         ,
	t.order_item_resource_id       ,
	t.order_item_resource_type      ,
	t.order_item_order_begin_time   ,
	t.order_item_order_end_time     ,
	t.order_item_account_type       ,
	t.order_item_account_charge_amt         ,
	t.virtual_operation_flag        ,
	'Y' as new_add_flag                  ,
	'Y' as boss_last_success_bill_flag   ,
	t.payment_amt / t.order_item_auth_qty  AS payment_amt,
	substr(regexp_replace(add_months(concat_ws('-', substr(t.order_item_order_begin_time, 1, 4), substr(t.order_item_order_begin_time, 5, 2), '01'), j.pos), '-', ''), 1, 6)  as bill_day
from (
select
	b.order_id                      ,
	b.order_last_upt_time           ,
	b.order_item_id                 ,
	b.payment_type                  ,
	b.currency_type                 ,
	b.order_status                  ,
	b.order_crt_day                 ,
	b.order_cancel_day              ,
	b.client_ip_region_id           ,
	b.payment_msisdn_region_id      ,
	b.order_msisdn_region_id        ,
	b.plat_id                       ,
	b.channel_id                    ,
	b.term_prod_id               ,
	b.term_prod_version_id       ,
	b.trig_order_program_id         ,
	b.trig_order_series_program_id  ,
	b.payment_msisdn                ,
	b.sp_id                         ,
	b.operation_code                ,
	b.goods_id                      ,
	b.goods_type                    ,
	b.goods_name                    ,
	b.service_code                  ,
	b.service_name                  ,
	b.order_crt_time                ,
	b.order_accept_time             ,
	b.order_payment_time            ,
	b.order_cancel_time             ,
	b.client_ip                     ,
	b.app_name                      ,
	b.order_user_id                 ,
	b.order_user_num                ,
	b.order_opr_user_id             ,
	b.order_opr_user_type           ,
	b.cancel_opr_user_id            ,
	b.cancel_opr_user_type          ,
	b.external_order_id             ,
	b.payment_id                    ,
	b.order_source_id               ,
	b.order_source_type             ,
	b.merchant_account              ,
	b.portal_type                   ,
	b.order_program_id              ,
	b.order_series_program_id       ,
	b.product_id                    ,
	b.product_pkg_id                ,
	b.sub_business_id               ,
	b.order_item_delivery_handler   ,
	b.order_item_delivery_status    ,
	b.order_item_auth_type          ,
	b.order_item_auth_unit          ,
	b.order_item_auth_qty           ,
	b.order_item_delivery_qty       ,
	b.order_item_unit_price         ,
	b.order_item_resource_id        ,
	b.order_item_resource_type      ,
	b.order_item_order_begin_time   ,
	b.order_item_order_end_time     ,
	b.order_item_account_type       ,
	b.order_item_account_charge_amt ,
	b.virtual_operation_flag        ,
	b.payment_amt                   ,
	split(rpad('0',cast(b.order_item_auth_qty as int)-1,'0'),'0') as month_arr
from rptdata.fact_order_item_detail b  --日新增订单
where b.src_file_day='${SRC_FILE_DAY}' and b.order_item_auth_type ='PERIOD' and b.order_item_auth_unit='MONTH' and b.order_status in ('5', '9')
) t
lateral view posexplode(t.month_arr) j as pos, c1
;

====================================================================================================================

set mapreduce.job.name=${DEST_TBL_SCHEMA}.fact_sim_bill_detail_${SRC_FILE_DAY};
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.dynamic.partition=true;
set hive.optimize.sort.dynamic.partition=true;

alter table ${DEST_TBL_SCHEMA}.fact_sim_bill_detail drop IF EXISTS partition(src_file_day='${SRC_FILE_DAY}');
--------------------
--非每月第一天逻
--------------------
insert overwrite table ${DEST_TBL_SCHEMA}.fact_sim_bill_detail partition (src_file_day='${SRC_FILE_DAY}', bill_day)
--boss合约和非包周期，只出一次，默认新增
select
	b.order_id                      ,
	b.order_last_upt_time           ,
	b.order_item_id                 ,
	b.payment_type                  ,
	b.currency_type                 ,
	b.order_status                  ,
	b.order_crt_day                 ,
	b.order_cancel_day              ,
	b.client_ip_region_id           ,
	b.payment_msisdn_region_id      ,
	b.order_msisdn_region_id        ,
	b.plat_id                       ,
	b.channel_id                    ,
	b.term_prod_id               ,
	b.term_prod_version_id       ,
	b.trig_order_program_id         ,
	b.trig_order_series_program_id  ,
	b.payment_msisdn                ,
	b.sp_id                         ,
	b.operation_code                ,
	b.goods_id                      ,
	b.goods_type                    ,
	b.goods_name                    ,
	b.service_code                  ,
	b.service_name                  ,
	b.order_crt_time                ,
	b.order_accept_time             ,
	b.order_payment_time            ,
	b.order_cancel_time             ,
	b.client_ip                     ,
	b.app_name                      ,
	b.order_user_id                 ,
	b.order_user_num                ,
	b.order_opr_user_id             ,
	b.order_opr_user_type           ,
	b.cancel_opr_user_id            ,
	b.cancel_opr_user_type          ,
	b.external_order_id             ,
	b.payment_id                    ,
	b.order_source_id               ,
	b.order_source_type             ,
	b.merchant_account              ,
	b.portal_type                   ,
	b.order_program_id              ,
	b.order_series_program_id       ,
	b.product_id                    ,
	b.product_pkg_id                ,
	b.sub_business_id               ,
	b.order_item_delivery_handler   ,
	b.order_item_delivery_status    ,
	b.order_item_auth_type          ,
	b.order_item_auth_unit          ,
	b.order_item_auth_qty           ,
	b.order_item_delivery_qty       ,
	b.order_item_unit_price         ,
	b.order_item_resource_id       ,
	b.order_item_resource_type      ,
	b.order_item_order_begin_time   ,
	b.order_item_order_end_time     ,
	b.order_item_account_type       ,
	b.order_item_account_charge_amt         ,
	b.virtual_operation_flag        ,
	'Y' as new_add_flag                  ,
	'Y' as boss_last_success_bill_flag   ,
	b.payment_amt                   ,
	'${SRC_FILE_DAY}' as bill_day
from rptdata.fact_order_item_detail b
where b.src_file_day='${SRC_FILE_DAY}' and b.order_status in ('5', '9')
and ((b.order_item_auth_type ='PERIOD' and b.order_item_auth_unit in ('HOUR', 'MINUTE')) or b.order_item_auth_type in ('TIMES', 'BOSS_MONTH'))
and nvl(b.boss_repeat_order_flag, 'N') = 'N'

union all
--非boss合约，默认全部是新增，按天拆分
select 
	t.order_id                      ,
	t.order_last_upt_time           ,
	t.order_item_id                 ,
	t.payment_type                  ,
	t.currency_type                 ,
	t.order_status                  ,
	t.order_crt_day                 ,
	t.order_cancel_day              ,
	t.client_ip_region_id           ,
	t.payment_msisdn_region_id      ,
	t.order_msisdn_region_id        ,
	t.plat_id                       ,
	t.channel_id                    ,
	t.term_prod_id               ,
	t.term_prod_version_id       ,
	t.trig_order_program_id         ,
	t.trig_order_series_program_id  ,
	t.payment_msisdn                ,
	t.sp_id                         ,
	t.operation_code                ,
	t.goods_id                      ,
	t.goods_type                    ,
	t.goods_name                    ,
	t.service_code                  ,
	t.service_name                  ,
	t.order_crt_time                ,
	t.order_accept_time             ,
	t.order_payment_time            ,
	t.order_cancel_time             ,
	t.client_ip                     ,
	t.app_name                      ,
	t.order_user_id                 ,
	t.order_user_num                ,
	t.order_opr_user_id             ,
	t.order_opr_user_type           ,
	t.cancel_opr_user_id            ,
	t.cancel_opr_user_type          ,
	t.external_order_id             ,
	t.payment_id                    ,
	t.order_source_id               ,
	t.order_source_type             ,
	t.merchant_account              ,
	t.portal_type                   ,
	t.order_program_id              ,
	t.order_series_program_id       ,
	t.product_id                    ,
	t.product_pkg_id                ,
	t.sub_business_id               ,
	t.order_item_delivery_handler   ,
	t.order_item_delivery_status    ,
	t.order_item_auth_type          ,
	t.order_item_auth_unit          ,
	t.order_item_auth_qty           ,
	t.order_item_delivery_qty       ,
	t.order_item_unit_price         ,
	t.order_item_resource_id       ,
	t.order_item_resource_type      ,
	t.order_item_order_begin_time   ,
	t.order_item_order_end_time     ,
	t.order_item_account_type       ,
	t.order_item_account_charge_amt         ,
	t.virtual_operation_flag        ,
	'Y' as new_add_flag                  ,
	'Y' as boss_last_success_bill_flag   ,
	t.payment_amt / t.order_item_auth_qty AS payment_amt,
	substr(regexp_replace(date_add(concat_ws('-', substr(t.order_item_order_begin_time, 1, 4), substr(t.order_item_order_begin_time, 5, 2), substr(t.order_item_order_begin_time, 7, 2)), j.pos), '-', ''), 1, 8) as bill_day
from (
select
	b.order_id                      ,
	b.order_last_upt_time           ,
	b.order_item_id                 ,
	b.payment_type                  ,
	b.currency_type                 ,
	b.order_status                  ,
	b.order_crt_day                 ,
	b.order_cancel_day              ,
	b.client_ip_region_id           ,
	b.payment_msisdn_region_id      ,
	b.order_msisdn_region_id        ,
	b.plat_id                       ,
	b.channel_id                    ,
	b.term_prod_id               ,
	b.term_prod_version_id       ,
	b.trig_order_program_id         ,
	b.trig_order_series_program_id  ,
	b.payment_msisdn                ,
	b.sp_id                         ,
	b.operation_code                ,
	b.goods_id                      ,
	b.goods_type                    ,
	b.goods_name                    ,
	b.service_code                  ,
	b.service_name                  ,
	b.order_crt_time                ,
	b.order_accept_time             ,
	b.order_payment_time            ,
	b.order_cancel_time             ,
	b.client_ip                     ,
	b.app_name                      ,
	b.order_user_id                 ,
	b.order_user_num                ,
	b.order_opr_user_id             ,
	b.order_opr_user_type           ,
	b.cancel_opr_user_id            ,
	b.cancel_opr_user_type          ,
	b.external_order_id             ,
	b.payment_id                    ,
	b.order_source_id               ,
	b.order_source_type             ,
	b.merchant_account              ,
	b.portal_type                   ,
	b.order_program_id              ,
	b.order_series_program_id       ,
	b.product_id                    ,
	b.product_pkg_id                ,
	b.sub_business_id               ,
	b.order_item_delivery_handler   ,
	b.order_item_delivery_status    ,
	b.order_item_auth_type          ,
	b.order_item_auth_unit          ,
	b.order_item_auth_qty           ,
	b.order_item_delivery_qty       ,
	b.order_item_unit_price         ,
	b.order_item_resource_id       ,
	b.order_item_resource_type      ,
	b.order_item_order_begin_time   ,
	b.order_item_order_end_time     ,
	b.order_item_account_type       ,
	b.order_item_account_charge_amt         ,
	b.virtual_operation_flag        ,
	b.payment_amt                   ,
	split(rpad('0',cast(b.order_item_auth_qty as int)-1,'0'),'0') as day_arr
from rptdata.fact_order_item_detail b
where b.src_file_day='${SRC_FILE_DAY}' and b.order_item_auth_type='PERIOD' and b.order_item_auth_unit='DAY' and b.order_status in ('5', '9')
) t
lateral view posexplode(t.day_arr) j as pos, c1

union all
--非boss合约，默认全部是新增，按月拆分
select
	t.order_id                      ,
	t.order_last_upt_time           ,
	t.order_item_id                 ,
	t.payment_type                  ,
	t.currency_type                 ,
	t.order_status                  ,
	t.order_crt_day                 ,
	t.order_cancel_day              ,
	t.client_ip_region_id           ,
	t.payment_msisdn_region_id      ,
	t.order_msisdn_region_id        ,
	t.plat_id                       ,
	t.channel_id                    ,
	t.term_prod_id               ,
	t.term_prod_version_id       ,
	t.trig_order_program_id         ,
	t.trig_order_series_program_id  ,
	t.payment_msisdn                ,
	t.sp_id                         ,
	t.operation_code                ,
	t.goods_id                      ,
	t.goods_type                    ,
	t.goods_name                    ,
	t.service_code                  ,
	t.service_name                  ,
	t.order_crt_time                ,
	t.order_accept_time             ,
	t.order_payment_time            ,
	t.order_cancel_time             ,
	t.client_ip                     ,
	t.app_name                      ,
	t.order_user_id                 ,
	t.order_user_num                ,
	t.order_opr_user_id             ,
	t.order_opr_user_type           ,
	t.cancel_opr_user_id            ,
	t.cancel_opr_user_type          ,
	t.external_order_id             ,
	t.payment_id                    ,
	t.order_source_id               ,
	t.order_source_type             ,
	t.merchant_account              ,
	t.portal_type                   ,
	t.order_program_id              ,
	t.order_series_program_id       ,
	t.product_id                    ,
	t.product_pkg_id                ,
	t.sub_business_id               ,
	t.order_item_delivery_handler   ,
	t.order_item_delivery_status    ,
	t.order_item_auth_type          ,
	t.order_item_auth_unit          ,
	t.order_item_auth_qty           ,
	t.order_item_delivery_qty       ,
	t.order_item_unit_price         ,
	t.order_item_resource_id       ,
	t.order_item_resource_type      ,
	t.order_item_order_begin_time   ,
	t.order_item_order_end_time     ,
	t.order_item_account_type       ,
	t.order_item_account_charge_amt         ,
	t.virtual_operation_flag        ,
	'Y' as new_add_flag                  ,
	'Y' as boss_last_success_bill_flag   ,
	t.payment_amt / t.order_item_auth_qty  AS payment_amt,
	substr(regexp_replace(add_months(concat_ws('-', substr(t.order_item_order_begin_time, 1, 4), substr(t.order_item_order_begin_time, 5, 2), '01'), j.pos), '-', ''),  1, 6) as bill_day
from (
select
	b.order_id                      ,
	b.order_last_upt_time           ,
	b.order_item_id                 ,
	b.payment_type                  ,
	b.currency_type                 ,
	b.order_status                  ,
	b.order_crt_day                 ,
	b.order_cancel_day              ,
	b.client_ip_region_id           ,
	b.payment_msisdn_region_id      ,
	b.order_msisdn_region_id        ,
	b.plat_id                       ,
	b.channel_id                    ,
	b.term_prod_id               ,
	b.term_prod_version_id       ,
	b.trig_order_program_id         ,
	b.trig_order_series_program_id  ,
	b.payment_msisdn                ,
	b.sp_id                         ,
	b.operation_code                ,
	b.goods_id                      ,
	b.goods_type                    ,
	b.goods_name                    ,
	b.service_code                  ,
	b.service_name                  ,
	b.order_crt_time                ,
	b.order_accept_time             ,
	b.order_payment_time            ,
	b.order_cancel_time             ,
	b.client_ip                     ,
	b.app_name                      ,
	b.order_user_id                 ,
	b.order_user_num                ,
	b.order_opr_user_id             ,
	b.order_opr_user_type           ,
	b.cancel_opr_user_id            ,
	b.cancel_opr_user_type          ,
	b.external_order_id             ,
	b.payment_id                    ,
	b.order_source_id               ,
	b.order_source_type             ,
	b.merchant_account              ,
	b.portal_type                   ,
	b.order_program_id              ,
	b.order_series_program_id       ,
	b.product_id                    ,
	b.product_pkg_id                ,
	b.sub_business_id               ,
	b.order_item_delivery_handler   ,
	b.order_item_delivery_status    ,
	b.order_item_auth_type          ,
	b.order_item_auth_unit          ,
	b.order_item_auth_qty           ,
	b.order_item_delivery_qty       ,
	b.order_item_unit_price         ,
	b.order_item_resource_id       ,
	b.order_item_resource_type      ,
	b.order_item_order_begin_time   ,
	b.order_item_order_end_time     ,
	b.order_item_account_type       ,
	b.order_item_account_charge_amt         ,
	b.virtual_operation_flag        ,
	b.payment_amt                   ,
	split(rpad('0',cast(b.order_item_auth_qty as int)-1,'0'),'0') as month_arr
from rptdata.fact_order_item_detail b
where b.src_file_day='${SRC_FILE_DAY}' and b.order_item_auth_type ='PERIOD' and b.order_item_auth_unit='MONTH' and b.order_status in ('5', '9')
) t
lateral view posexplode(t.month_arr) j as pos, c1
;